services:
  postgres:
    build:
      context: .
      dockerfile_inline: |
        FROM postgres:latest
        COPY <<-EOT '/docker-entrypoint-initdb.d/!.sh'
          #!/bin/bash
          set -e
          psql -U "\$$POSTGRES_USER" -d "\$$POSTGRES_DB" -c "ALTER SCHEMA public RENAME TO \$$POSTGRES_USER;"
          psql -U "\$$POSTGRES_USER" -d "\$$POSTGRES_DB" -c "ALTER USER \$$POSTGRES_USER SET search_path TO \$$POSTGRES_USER;"
        EOT
        COPY ./*.sql /docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  volumes:
    postgres-data:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}